//used in the dashboard page.jsx
const data = [
  {
    full_heading: "Introduction to FMS (Flight Management System) and Autoflight",
    short_heading: "Introduction to FMS",
    path: "/dashboard/general",
    c_id: "c1",
    modules: [
      {
        id: "md1",
        entry: "1.0",
        heading: "Introduction to FMS (The Brains of Aircraft)",
        title: "What is FMS?",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md2",
        entry: "2.0",
        heading: "Preflight Planning",
        title: "Setting Up the Preflight Phase.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md3",
        entry: "3.0",
        heading: "In-Flight Procedures",
        title: "FPL page & LNAV/VNAV Exercises.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md4",
        entry: "4.0",
        heading: "Handling In-Flight Scenarios",
        title: "Diversions and Alternate Airports.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md5",
        entry: "5.0",
        heading: "Airline-Specific Procedures (Optional)",
        title: "Custom FMC Procedures",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md6",
        entry: "6.0",
        heading: "Troubleshooting and Advanced Features",
        title:
          "Practice troubleshooting pre-programmed errors in the simulator.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
    ],
  },
  {
    full_heading: "Boeing 737",
    short_heading: "Introduction to FMS",
    c_id: "c2",
    path: "/dashboard/boeing_737",
    modules: [
      {
        id: "md1",
        entry: "1.0",
        heading: "Introduction to FMS (The Brains of Aircraft)",
        title: "What is FMS?",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md2",
        entry: "2.0",
        heading: "Preflight Planning",
        title: "Setting Up the Preflight Phase.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md3",
        entry: "3.0",
        heading: "In-Flight Procedures",
        title: "FPL page & LNAV/VNAV Exercises.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md4",
        entry: "4.0",
        heading: "Handling In-Flight Scenarios",
        title: "Diversions and Alternate Airports.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md5",
        entry: "5.0",
        heading: "Airline-Specific Procedures (Optional)",
        title: "Custom FMC Procedures",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md6",
        entry: "6.0",
        heading: "Troubleshooting and Advanced Features",
        title:
          "Practice troubleshooting pre-programmed errors in the simulator.",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
    ],
  },{
    full_heading: "Airbus A320",
    short_heading: "Airbus A320",
    c_id: "c3",
    path: "/dashboard/airbus_a320",
    modules: [
      {
        id: "md1",
        entry: "1.0",
        heading: "Overview",
        title: "MCDU component overview",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md2",
        entry: "2.0",
        heading: "MCDU Menu Pages",
        title: "MCDU Preflight Phase menu",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: true,
      },
      {
        id: "md3",
        entry: "3.0",
        heading: "INIT Page A Functions",
        title: "Route Selection",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md4",
        entry: "4.0",
        heading: "Lateral Revision Pages",
        title: "Flight Planning Page",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md5",
        entry: "5.0",
        heading: "Depature Pages",
        title: "Departure selection page",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md6",
        entry: "6.0",
        heading: "Arrival Pages",
        title:
          "Arrival Selection",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
      {
        id: "md7",
        entry: "7.0",
        heading: "Route Selection Pages",
        title:
          "Select Primary and alternate route",
        timing: "08:48",
        docs: 3,
        quizzes: 2,
        completed: false,
      },
    ],
  },
];

export default data;
