const data = [
  {
    id: "md1",
    entry: "1.0",
    heading: "Introduction to FMS (The Brains of Aircraft)",
    title: "What is FMS?",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: true,
  },
  {
    id: "md2",
    entry: "2.0",
    heading: "Preflight Planning",
    title: "Setting Up the Preflight Phase.",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: true,
  },
  {
    id: "md3",
    entry: "3.0",
    heading: "In-Flight Procedures",
    title: "FPL page & LNAV/VNAV Exercises.",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: false,
  },
  {
    id: "md4",
    entry: "4.0",
    heading: "Handling In-Flight Scenarios",
    title: "Diversions and Alternate Airports.",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: false,
  },
  {
    id: "md5",
    entry: "5.0",
    heading: "Airline-Specific Procedures (Optional)",
    title: "Custom FMC Procedures",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: false,
  },
  {
    id: "md6",
    entry: "6.0",
    heading: "Troubleshooting and Advanced Features",
    title: "Practice troubleshooting pre-programmed errors in the simulator.",
    timing: "08:48",
    docs: 3,
    quizzes: 2,
    completed: false,
  },
];


export default data;